# Generated by Django 5.0 on 2025-04-28 22:28

from django.db import migrations, models
import django.db.models.deletion

def forwards_func(apps, schema_editor):
    # Create default categories if needed
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_transaction_date_budget_category_and_more'),  # Update this to match your previous migration
    ]

    operations = [
        # Create Category table if it doesn't exist
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        # Add category_id to Transaction if it doesn't exist
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.category'),
        ),
    ]