# Generated by Django 5.0 on 2025-04-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_budgetnotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="year",
            field=models.DecimalField(decimal_places=0, default=2025, max_digits=4),
        ),
    ]
